version: '2'
services:
  hydrusclient:
    image: suikaprof/hydrusclient:latest
    container_name: hydrusclient_test
    restart: unless-stopped
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - /Users/seamusreynolds/Sync/hydrusdbs/workmac:/opt/hydrus/db
    tmpfs:
      - /tmp #optional for SPEEEEEEEEEEEEEEEEEEEEEEEEED and less disk access
    ports:
      - 6800:6800   #noVNC
      - 6900:6900   #VNC
      - 45908:45908 #Booru
      - 45909:45909 #API
#  hydrus-web:
#    image: suika/hydrus-web:latest
#    container_name: hydrus-web
#    restart: always
#    ports:
#      - 8080:80 # READ